// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchDog.DBContexts;

namespace watchdog.Migrations
{
    [DbContext(typeof(WatchDogDBContext))]
    [Migration("20210131070021_LastCheckin")]
    partial class LastCheckin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WatchDog.Models.WatchDogItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FrequencyMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCheckin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Name");

                    b.ToTable("WatchDogItems");
                });
#pragma warning restore 612, 618
        }
    }
}
